version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Entering install phase...
      - echo Nothing to do now
  build:
    commands:
      - echo Build started on `date`
      - gradle build
artifacts:
  type: zip
  files:
    - 'build/libs/*.jar'