server:
  port: ${PORT:8080}

spring:
  datasource:
    dataSourceClassName: org.h2.jdbcDataSource
    url: jdbc:h2:mem:myShop;DB_CLOSE_DELAY=-1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true